version: "3.8"
services:
    #PHP service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - semestralne_zadanie
            - redis

    #Database server
    semestralne_zadanie:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=semestralne_zadanie
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 5
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
        ports:
            - 6379:6379

volumes :
    db-data : ~